apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-index
data:
  index.html: |
    <html>
    <h1>Hello world</h1>
    </html
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: webserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
        fsGroup: 3000
      containers:
        - name: webserver
          image: nginxinc/nginx-unprivileged:latest
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: nginx-index
              mountPath: /usr/share/nginx/html/
      volumes:
        - name: nginx-index
          configMap:
            name: webserver-index
