apiVersion: v1
kind: ConfigMap
metadata:
  name: webserver-index
data:
# Add your index file here
---
apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
# Specify your service here
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    # Specify your container here
